FROM node:18

WORKDIR /app

COPY package.json ./

RUN npm cache clean --force && npm install

COPY . .

EXPOSE 3000

ENV AWS_REGION=${AWS_REGION}
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

CMD ["node", "server.js"]
